# James Cooper
# Assignment 2
# CSC 478-710

##        Problem 1

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [8]:
import os
os.getcwd()

'C:\\Users\\James Cooper\\Desktop\\DePaul\\Programming Machine Learning\\Assignment2'

In [9]:
os.chdir("C:\Users\James Cooper\Desktop\DePaul\Programming Machine Learning\Assignment2")
os.getcwd()

'C:\\Users\\James Cooper\\Desktop\\DePaul\\Programming Machine Learning\\Assignment2'

### *Create your own KNN classifier function. Your classifier should allow as input the training data matrix, the training labels, the instance to be classified, the value of K, and should return the predicted class for the instance and the top K neighbors. Your classifier should work with Euclidean distance as well as Cosine Similarity. You may create two separate classifiers, or add this capability as a parameter for the classifier function.*

In [10]:
trainmatrix = pd.read_csv("trainMatrixModified.txt",delimiter="\t", header=None)

In [11]:
#Matrix is in termxdocument
trainmatrix.head()


0    1    2    3    4    5    6    7    8    9   ...   790  791  792  793  \
0  2.0  0.0  0.0  2.0  2.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
1  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  3.0  0.0   
2  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  2.0  1.0  1.0  1.0 ...   1.0  1.0  1.0  1.0   
4  8.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  2.0  0.0   

   794  795  796  797  798  799  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  1.0  1.0  1.0  1.0  1.0  1.0  
4  0.0  0.0  0.0  0.0  0.0  1.0  

[5 rows x 800 columns]

In [12]:
#0 = rows
#1 = columns
numterms=trainmatrix.shape[0]
numdocs=trainmatrix.shape[1]
print "Number of terms = ", numterms
print "Number of docs = ", numdocs


Number of terms =  5500
Number of docs =  800


In [13]:
trainmatrix_pdtr = trainmatrix.T
trainmatrix_pdtr.head()

0     1     2     3     4     5     6     7     8     9     ...   5490  \
0   2.0   2.0   2.0   1.0   8.0   6.0   2.0   8.0   2.0   4.0  ...    0.0   
1   0.0   0.0   0.0   1.0   1.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
2   0.0   0.0   0.0   1.0   0.0   0.0   0.0   2.0   0.0   1.0  ...    0.0   
3   2.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   
4   2.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...    0.0   

   5491  5492  5493  5494  5495  5496  5497  5498  5499  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 5500 columns]

In [14]:
#Transpose to docxterm matrix
trainmatrix_Tr = np.array(trainmatrix.T, dtype = int)
trainmatrix_Tr

array([[2, 2, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
trainmatrix_Tr2 = np.array(trainmatrix.T, np.int64)
trainmatrix_Tr2

array([[2, 2, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
trainmatrix_Tr2.shape

(800L, 5500L)

In [17]:
numdocs_T = trainmatrix_Tr2.shape[0]
numterms_T = trainmatrix_Tr2.shape[1]
print numdocs_T
print numterms_T

800
5500


In [18]:
#Import the classes for the data: 0 = Microsoft, 1 = Hockey
trainlabels = pd.read_csv("trainClasses.txt",delimiter="\t", header=None)
trainlabels_ix = trainlabels.iloc[:,1:]
trainlabels_ix.head()


1
0  0
1  1
2  0
3  1
4  0

In [19]:
#Turn class labels into a numpy array
trainlabelarray = np.array(trainlabels_ix)
trainlabelarray

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [20]:
#Using the untransposed matrix (trainmatrix) to count the frequency of terms by document (count by columns)
freqbyterm = trainmatrix.sum(axis=1)
freqbyterm_int = freqbyterm.astype(np.int64)
print freqbyterm_int
freqbyterm.to_csv('freqbyterm.csv')

0       102
1        11
2        22
3       959
4       222
5        84
6       108
7       262
8        55
9       318
10       69
11       41
12      148
13      128
14      128
15      146
16      201
17       39
18      159
19        6
20      189
21       65
22      227
23       89
24       40
25      329
26       43
27       18
28       54
29        8
       ... 
5470      3
5471      4
5472      3
5473      3
5474      3
5475      3
5476      3
5477      3
5478      2
5479      4
5480      3
5481      2
5482      3
5483      3
5484      5
5485      4
5486      3
5487      2
5488      2
5489      2
5490      3
5491      2
5492      1
5493      2
5494      3
5495      3
5496      3
5497      2
5498      2
5499      2
Length: 5500, dtype: int64


In [21]:
#Import the terms file
terms = pd.read_csv("modifiedterms.txt", header=None)
terms2 = terms.iloc[:,0]
print terms2
terms2.to_csv('terms.csv')

0                       david
1                         rex
2                        wood
3                     subject
4                        call
5                     librari
6                       creat
7                      widget
8                     multipl
9                        time
10                        dai
11                        ago
12                       post
13                   question
14                        try
15                   function
16                        set
17                        app
18                      point
19                 xtappiniti
20                       help
21                       have
22                    problem
23                      littl
24                       test
25                    program
26                      close
27                      model
28                       real
29                     actual
                ...          
5470                 director
5471                  overlap
5472      

In [22]:
#Put the frequencies together in a dictionary
dictTD = {}
for i in range(numterms_T):
    dictTD[terms2[i]] = freqbyterm_int[i]
print sorted(dictTD.items())
sortedTD = sorted(dictTD.values(), reverse=True)
print sortedTD.head()

[('00', 102), ('000', 34), ('01', 30), ('02', 28), ('0223', 7), ('0228', 2), ('03', 29), ('04', 26), ('0444', 5), ('05', 18), ('06', 23), ('07', 23), ('08', 14), ('09', 14), ('0ha', 3), ('0xff', 2), ('10', 249), ('100', 52), ('1000', 10), ('10000', 3), ('1006', 5), ('1008', 7), ('101', 18), ('1010', 3), ('1017', 5), ('1018', 3), ('1019', 2), ('102', 15), ('1020', 8), ('1021', 3), ('1024', 3), ('103', 16), ('1033', 5), ('1038', 4), ('104', 22), ('1040', 4), ('1043', 2), ('1046', 5), ('1049', 4), ('105', 14), ('10510', 3), ('1053', 4), ('1054', 5), ('1057', 3), ('106', 12), ('1062', 3), ('1063', 3), ('1067', 3), ('107', 8), ('1071', 4), ('1072', 3), ('1076', 4), ('108', 12), ('1082', 5), ('109', 8), ('1096', 3), ('10th', 3), ('10x20', 3), ('11', 178), ('110', 23), ('1109', 3), ('111', 21), ('11150', 4), ('112', 17), ('1120', 3), ('1121', 5), ('1126', 3), ('113', 12), ('1136', 3), ('114', 13), ('1140', 5), ('1142', 3), ('1146', 5), ('1149', 4), ('115', 10), ('1156', 3), ('116', 13), ('117

AttributeError: 'list' object has no attribute 'head'

In [29]:
#Classifier should allow training data matrix (TM), Training Lables (TL), Instance to be classified (x), and the value
#of K
#def knn_newsgroup(TM, TL, x, K):

#This function takes an instance to be searched for (x) - vector
#Then it takes your document x term matrix (D)
#K Specifies your number of neighbors (K)
#Measure - if set to 0 you are using Euclidean, set to 1 you use the inverse of Cosine similarity
def knn_search(x, D, K, measure):
    
    if measure == 0:
        #euclidean distance from other points - subtract x from each row in D, take the sum of the squares, and use the 
        #square root - axis = 1 here because we are adding up all the terms
        dists = np.sqrt(((D - x)**2).sum(axis=1))
        
    elif measure == 1:
        #find vector norm in each instance in D as well as the vecotr norm of x
        #Cosine similarity is the dot product divided by the multiple of the norms
        #D_norm = normalized vectors of D (all rows)
        D_norm = np.array([np.linalg.norm(D[i]) for i in range(len(D))])
        x_norm = np.linalg.norm(x)
        #Divide the dot product of x and each instance in D by the product of the two norms
        #np.dot gives the dot product of two vectors divided by a comma
        #D = the docxterm matrix
        #x = instance we want to categorize
        sims = np.dot(D,x)/(D_norm * x_norm)
        #distance measure will be the inverse of cosine similarity
        dists = 1 - sims
        #We want to return a sorted version of our distances
    idx = np.argsort(dists)
    
    return idx[:K], trainlabelarray[idx[:K]], dists

    
    

In [23]:
#Import test matrix to run KNN function on
testmatrix = pd.read_csv("testMatrixModified.txt",delimiter="\t", header=None)
testmatrix.head()

0    1    2    3    4    5    6    7    8    9   ...   190  191  192  193  \
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0  0.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  2.0  1.0  1.0  1.0 ...   1.0  2.0  1.0  1.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0 ...   0.0  0.0  0.0  0.0   

   194  195  196  197  198  199  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  1.0  1.0  1.0  1.0  1.0  1.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 200 columns]

In [24]:
testmatrix.shape

(5500, 200)

In [25]:
testmatrix_Tr = testmatrix.T
testmatrix_Tr.shape

(200, 5500)

In [26]:
t = np.array(testmatrix_Tr.iloc[0])
t

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [30]:
x, y, dist = knn_search(t, trainmatrix_Tr2, 5, 1)
print x

[685 628 667 152 427]


In [31]:
print y


[[1]
 [1]
 [1]
 [1]
 [1]]


In [32]:
dist

array([ 0.92709494,  0.79673989,  0.9320382 ,  0.89790716,  0.94654139,
        0.75100253,  0.87022016,  0.83936495,  0.8663802 ,  0.83658124,
        0.85889206,  0.91046232,  0.967053  ,  0.8674656 ,  0.85682474,
        0.84202209,  0.9559169 ,  0.95930309,  0.81201636,  0.97654623,
        0.9759507 ,  0.82749758,  0.93546895,  0.94852203,  0.89320834,
        0.9601543 ,  0.97054574,  0.9028059 ,  0.86947952,  0.92402623,
        0.86401406,  0.9456762 ,  0.82902992,  0.76739778,  0.86165711,
        0.96686511,  0.86091087,  0.9020568 ,  0.9759507 ,  0.95663844,
        0.97550939,  0.92957962,  0.88366959,  0.95588511,  0.98953954,
        0.95998862,  0.93637152,  0.89704406,  0.95616007,  0.9879854 ,
        0.9022188 ,  0.93387535,  0.84695651,  0.93428479,  0.97550939,
        0.92957618,  0.92167876,  0.81023414,  0.9721565 ,  0.92547176,
        0.96103567,  0.90908324,  0.94943321,  0.84305278,  0.93303296,
        0.87675215,  0.87719859,  0.93699842,  0.83269659,  0.92

In [34]:
print x
print '\n'
print trainlabelarray[x]



[685 628 667 152 427]


[[1]
 [1]
 [1]
 [1]
 [1]]


In [35]:
print dist[trainlabelarray]

[[ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.92709494]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673989]
 [ 0.79673

In [36]:
nlabel = trainlabels_ix.iloc[x]
nlabel

1
685  1
628  1
667  1
152  1
427  1

In [37]:
nlabel.count()

1    5
dtype: int64

### *Create a function to compute the classification accuracy over the test data set (ratio of correct predictions to the number of test instances). This function will call the classifier function on all the test instances and in each case compares the actual test class label to the predicted class label.*

In [38]:
from collections import Counter
print Counter(nlabel)

Counter({1: 1})


In [39]:
x_Euc, y_Euc, dist = knn_search(t, trainmatrix_Tr2, 5, 0)
print x_Euc

[685 628 703 266 510]


In [40]:
print y_Euc

[[1]
 [1]
 [1]
 [1]
 [1]]


In [41]:
print dist

[  30.28200786   17.3781472    17.32050808   16.4924225    16.91153453
   26.45751311   20.39607805   16.85229955   17.4642492    22.93468988
   18.97366596   20.22374842   46.62617291   20.78460969   16.91153453
   18.24828759   17.60681686   17.97220076   19.72308292   20.51828453
   16.46207763   20.0748599    16.43167673   17.02938637   18.68154169
   21.9544984    16.82260384   17.40689519   16.97056275   54.69917732
   18.52025918   19.77371993   16.09347694   24.63736999   18.38477631
   17.2626765    19.10497317   26.34387974   15.87450787  219.98863607
   16.43167673   20.59126028   17.80449381   30.98386677   16.79285562
   23.04343724   16.79285562   16.673332     24.0208243    45.01110974
   20.61552813   17.43559577   18.97366596   15.93737745   16.43167673
   16.52271164   27.94637722   18.43908891   16.97056275   19.5192213
   16.2788206    23.97915762   17.08800749   19.20937271   18.78829423
   18.22086716   21.04756518   18.13835715   19.72308292   15.87450787
   17.5

In [42]:
testvecs = len(t)
print testvecs

5500


In [43]:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()     
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

In [44]:
errorCount = 0.0
for i in range(testvecs):
    #give knn.classify0 the first row of the vs_test_norm data, the training data, vs_target_train which are the labels
    #and k = 3
    classifierResult = classify0(testmatrix_Tr[i,:], trainmatrix_Tr2, trainlabelarray, 5)
    print "the classifier came back with: %s, the real answer is: %s" % (classifierResult, trainlabelarray[i])
    if (classifierResult != trainlabelarray[i]): errorCount += 1.0

#divide the count of errors by the total number of test cases
print "the total error rate is: %f" %(errorCount/float(numtestvecs))

TypeError: unhashable type

### *Run your accuracy function on a range of values for K in order to compare accuracy values for different numbers of neighbors. Do this both using Euclidean Distance as well as Cosine similarity measure. [For example, you can try evaluating your classifiers on a range of values of K from 1 through 20 and present the results as a table or a graph].*

In [45]:
training = pd.read_csv("trainMatrixModified.txt",delimiter="\t", header=None)
trainlabs = pd.read_csv("trainClasses.txt",delimiter="\t", header=None)
test = pd.read_csv("testMatrixModified.txt",delimiter="\t", header=None)
testlabs = pd.read_csv("testClasses.txt", delimiter="\t", header=None)

def Kaccuracy(training, trainlabs, test, testlabs, k, measure):
    correct = 0
    for i in range(test.shape[0]):
        predict = knn_search(test[i], training, k, measure)
        if predict[0] == testlabs[i,:][1]:
            correct += 1
    
    accuracy_rate = float(correct)/float(test.shape[0])
    return accuracy_rate
        


In [46]:
Kaccuracy(training, trainlabs, test, testlabs, 5, 1)

KeyError: 800L

### *Using Python, modify the training and test data sets so that term weights are converted to TFxIDF weights (instead of raw term frequencies). [See class notes on Text Categorization]. Then, rerun your evaluation on the range of K values (as above) and compare the results to the results without using TFxIDF weights.*

In [ ]:
DF = np.array([(trainmatrix!=0).sum(1)]).T
print DF

In [ ]:
Ndocs = trainmatrix.shape[1]
Matrix_1s = np.ones(np.shape(trainmatrix), dtype=float)*Ndocs
Matrix_1s

In [ ]:
IDF = np.log2(np.divide(Matrix_1s, DF))

In [ ]:
print IDF

In [ ]:
TD_IDF = trainmatrix * IDF
pd.set_option("display.precision", 2)
TD_IDF.shape

In [ ]:
def knn_search(x, D, K, measure):
    
    if measure == 0:
        #euclidean distance from other points - subtract x from each row in D, take the sum of the squares, and use the 
        #square root - axis = 1 here because we are adding up all the terms
        dists = np.sqrt(((D - x)**2).sum(axis=1))
        
    elif measure == 1:
        #find vector norm in each instance in D as well as the vecotr norm of x
        #Cosine similarity is the dot product divided by the multiple of the norms
        #D_norm = normalized vectors of D (all rows)
        D_norm = np.array([np.linalg.norm(D[i]) for i in range(len(D))])
        x_norm = np.linalg.norm(x)
        #Divide the dot product of x and each instance in D by the product of the two norms
        #np.dot gives the dot product of two vectors divided by a comma
        #D = the docxterm matrix
        #x = instance we want to categorize
        sims = np.dot(D,x)/(D_norm * x_norm)
        #distance measure will be the inverse of cosine similarity
        dists = 1 - sims
        #We want to return a sorted version of our distances
    idx = np.argsort(dists)
    
    return idx[:K], trainlabelarray[idx[:K]], dists

In [ ]:
x1 = np.array(testmatrix_Tr.iloc[45][:])
x1

In [ ]:
x_TDIDF = x1 * IDF.T[0]
print x_TDIDF

In [ ]:
DT_IDF = TD_IDF.T
DT_IDF.shape

In [ ]:
DT2_IDF = np.array(DT_IDF)

In [ ]:
x, y, dist = knn_search(x_TDIDF, DT_IDF, 5, 1)
print x

In [ ]:
print DT2_IDF[x]
print "\n"
print "Distances to x: ", np.sort(y)[0:5]

## Problem 2

> ### *Load and preprocess the data using Numpy or Pandas and the preprocessing functions from scikit-learn. Specifically, you need to separate the target attribute ("pep") from the portion of the data to be used for training and testing. You will need to convert the selected dataset into the Standard Spreadsheet format (scikit-learn functions generally assume that all attributes are in numeric form). Finally, you need to split the transformed data into training and test sets (using 80%-20% randomized split). [Review Ipython Notebook examples from Week 4 for different ways to perform these tasks.]*

In [ ]:
bankdata = pd.read_csv('bank_data.csv', index_col=0)
bankdata.head()

In [ ]:
#Create a random permutation of the data
bankpermutation = bankdata.reindex(np.random.permutation(bankdata.index))
bankpermutation.head(10)

In [ ]:
len(bankpermutation)

In [ ]:
#Isolate target variable
bank_target = bankpermutation.pep
bank_target.head(10)

In [ ]:
bank_names = bankpermutation.columns.values
bank_names

In [ ]:
#We need to use dummy variables for categorical attributes
bank_dum = pd.get_dummies(bankpermutation[['age', 'income', 'children', 'gender', 'region', 'married', 'car',
       'savings_acct', 'current_acct', 'mortgage']])
bank_dum.head(10)


In [ ]:
#Next step is to split the data
#To be able to evaluate the accuracy of our predictions, we will split the data into 
#training and test sets. In this case, we will use 80% for training and the remaining 20% for testing. 
#Note that we must also do the same split to the target attribute.
#So vs[:tsize ] = 0 to tsize

tpercent = 0.8
tsize = int(np.floor(tpercent * len(bank_dum)))
bank_dum_train = bank_dum[:tsize]
bank_dum_test = bank_dum[tsize:]

In [ ]:
print bank_dum_train.shape
print bank_dum_test.shape

In [ ]:
#We need to do the same for the target attribute
bank_target_train1 = bank_target[0:int(tsize)]
bank_target_test1 = bank_target[int(tsize):len(bank_target)]

In [ ]:
print bank_target_train1.shape
print bank_target_test1.shape

> ### *Run scikit-learn's KNN classifier on the test set. Note: in the case of KNN, you must first normalize the data so that all attributes are in the same scale (normalize so that the values are between 0 and 1). Generate the confusion matrix (visualize it using Matplotlib), as well as the classification report. Also, computing the average accuracy score. Experiment with different values of K and the weight parameter for KNN to see if you can improve accuracy (you do not need to provide the details of all of your experimentation, but provide a short discussion what parameters worked best).*

In [ ]:
from sklearn import preprocessing

In [ ]:
#We create a min max object, we use it by calling the fit function - we are fitting the minmax normalization to the training data
min_max_scale = preprocessing.MinMaxScaler()
min_max_scale.fit(bank_dum_train)

In [ ]:
#So we apply the normalization to the data
#Note that it is possible that the min max  will be different in the test and training, so you may have slightly
#different scales
bank_train_norm = min_max_scale.fit_transform(bank_dum_train)
bank_test_norm = min_max_scale.fit_transform(bank_dum_test)

In [ ]:
np.set_printoptions(precision=2, linewidth=100)
bank_train_norm[:10]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn6 = KNeighborsClassifier(n_neighbors = 6)

In [ ]:
knn6.fit(bank_train_norm, bank_target_train1)

In [ ]:
pred_1 = knn6.predict(bank_test_norm)
print("Test set precitions:\n {}".format(pred_1))

In [ ]:
knn6.score(bank_test_norm, bank_target_test1)

In [ ]:
knn4 = KNeighborsClassifier(n_neighbors = 4)

In [ ]:
knn4.fit(bank_train_norm, bank_target_train1)

In [ ]:
pred_2 = knn4.predict(bank_test_norm)
print("Test set precitions:\n {}".format(pred_2))

In [ ]:
knn4.score(bank_test_norm, bank_target_test1)

In [ ]:
knn3 = KNeighborsClassifier(n_neighbors = 3)

In [ ]:
knn3.fit(bank_train_norm, bank_target_train1)

In [ ]:
pred_3 = knn3.predict(bank_test_norm)
print("Test set precitions:\n {}".format(pred_3))

In [ ]:
knn3.score(bank_test_norm, bank_target_test1)

In [ ]:
nn = np.arange(1,9)
train = np.empty(len(nn))
test = np.empty(len(nn))

for i, k in enumerate(nn):
    knneighb = KNeighborsClassifier(n_neighbors = k)
    knn6.fit(bank_train_norm, bank_target_train1)
    
    train[i] = knn6.score(bank_train_norm, bank_target_train1)
    
    test[i] = knn6.score(bank_test_norm, bank_target_test1)
    
    

In [ ]:
plt.plot(nn, train, label = 'Training')
plt.plot(nn, test)
plt.show()

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(bank_target_test1, pred_3)

### *Repeat the classification using scikit-learn's decision tree classifier (using the default parameters) and the naive Bayes (Gaussian) classifier. As above, generate the confusion matrix, classification report, and average accuracy score for each classifier. For each model, compare the average accuracry scores on the test and the training data sets. What does the comparison tell you in terms of bias-variance trade-off?*

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.cross_validation import train_test_split
from sklearn import neighbors, tree, naive_bayes
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
bank_target.head()

In [ ]:
bank_dum.head()

In [ ]:
bank_train, bank_test, bank_target_train, bank_target_test = train_test_split(bank_dum, bank_target, test_size=0.2, random_state=33)
print bank_test.shape
bank_test[0:5]

In [ ]:
dectree = tree.DecisionTreeClassifier(criterion='entropy', min_samples_split=3) 

In [ ]:
dectree = dectree.fit(bank_train, bank_target_train)

In [ ]:
dtpred_test = dectree.predict(bank_test)
print dtpred_test

In [ ]:
print dectree.score(bank_test, bank_target_test)

In [ ]:
print dectree.score(bank_train, bank_target_train)

In [ ]:
print(classification_report(bank_target_test, dtpred_test))

In [ ]:
bank_conf = confusion_matrix(bank_target_test, dtpred_test)
print bank_conf

In [ ]:
import pylab as plt
%matplotlib inline
plt.matshow(bank_conf)
plt.title('Confusion matrix')
plt.colorbar()
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

In [ ]:
bayes = naive_bayes.GaussianNB()
bayes = bayes.fit(bank_train, bank_target_train)
bayes_predict = bayes.predict(bank_test)
print bayes_predict


In [ ]:
print bayes.score(bank_train, bank_target_train)

In [ ]:
print bayes.score(bank_test, bank_target_test)

#### The decision tree showed the most accuracy here with 99% on the training data and 84% on the test data. This does give an indication of overfitting here since the training data is quite a bit more accurate than the test data. More investigation and possible pruning would be needed for this analysis.

## Problem 3

In [ ]:
import os
os.chdir('C:\Users\James Cooper\Desktop\DePaul\Programming Machine Learning\Assignment2')
os.getcwd()

###  *Preprocessing and data analysis:*

Examine the data for missing values. In case of categorical attributes, remove instances with missing values. In the case of numeric attributes, impute and fill-in the missing values using the attribute mean.

Examine the characteristics of the attributes, including relevant statistics for each attribute, histograms illustrating the distribtions of numeric attributes, bar graphs showing value counts for categorical attributes, etc.

Perform the following cross-tabulations (including generating bar charts): education+race, work-class+income, work-class+race, and race+income. In the latter case (race+income) also create a table or chart showing percentages of each race category that fall in the low-income group. Discuss your observations from this analysis.

Compare and contrast the characteristics of the low-income and high-income categories across the different attributes. 

In [ ]:
adult_mod = pd.read_csv('adult-modified.csv', na_values=['?'])
adult_mod.head(20)

In [ ]:
adult_mod.shape

In [ ]:
adult_mod.columns

In [ ]:
adult_mod.info()

In [ ]:
adult_mod.describe(include='all')

In [ ]:
#Rows where age is null
adult_mod[adult_mod.age.isnull()]

In [ ]:
#Replace age null values with the mean value
mean_age = adult_mod.age.mean()
adult_mod.age.fillna(mean_age, axis=0, inplace=True)

In [ ]:
adult_mod[adult_mod.age.isnull()]

In [ ]:
#values are now at 10000
adult_mod.describe(include='all')

In [ ]:
adult_mod[adult_mod.workclass.isnull()]

In [ ]:
adult_mod.dropna(axis=0, inplace=True)

In [ ]:
#All rows with workclass = null are now deleted
adult_mod.describe(include='all')

In [ ]:
adult_mod['workclass'].value_counts()

In [ ]:
adult_mod['race'].value_counts()

In [ ]:
adult_mod['income'].value_counts()

In [ ]:
adult_mod.groupby(adult_mod['workclass']).describe()

In [ ]:
#Histogram of age

plt.hist(adult_mod['age'], bins=9, edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution')
plt.show()

In [ ]:
#Education Histogram

plt.hist(adult_mod['education'], bins=6, edgecolor='black')
plt.xlabel('Education Level')
plt.ylabel('Frequency')
plt.title('Education Distribution')
plt.show()

In [ ]:
#Hours per week worked

plt.hist(adult_mod['hours-per-week'], bins=6, edgecolor='black')
plt.xlabel('Hours Worked per Week')
plt.ylabel('Frequency')
plt.title('Job Hours')
plt.show()

In [ ]:
#Working Class

workclass_count = pd.value_counts(adult_mod['workclass'].values)
print workclass_count

workclass_count.plot.bar()
plt.xlabel('Work Class Category')
plt.ylabel('Count')
plt.title('Working Class Distribution')

In [ ]:
#Martial Status

marital_count = pd.value_counts(adult_mod['marital-status'].values)
print marital_count

marital_count.plot.bar()
plt.xlabel('Martial Status')
plt.ylabel('Count')
plt.title('Married vs. Not Married')

In [ ]:
#Race

race_count = pd.value_counts(adult_mod['race'].values)
print race_count

race_count.plot.bar()
plt.xlabel('Race')
plt.ylabel('Count')
plt.title('Demographic')

In [ ]:
#Gender

gender_count = pd.value_counts(adult_mod['sex'].values)
print gender_count

gender_count.plot.bar()
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Gender Distribution')

In [ ]:
#Income

income_count = pd.value_counts(adult_mod['income'].values)
print income_count

income_count.plot.bar()
plt.xlabel('Income')
plt.ylabel('Count')
plt.title('Income Distribution')

In [ ]:
cross1 = pd.crosstab(adult_mod['education'], adult_mod['race'])
print cross1

plt.rcParams['figure.figsize'] = 16, 12
plt.show(cross1.plot(kind='bar', title='Education and Race'))

In [ ]:
cross2 = pd.crosstab(adult_mod['workclass'], adult_mod['income'])
print cross2

plt.rcParams['figure.figsize'] = 10,7
plt.show(cross2.plot(kind='bar', title='Income by Workclass'))

In [ ]:
cross3 = pd.crosstab(adult_mod['race'], adult_mod['workclass'])
print cross3

plt.rcParams['figure.figsize'] = 10, 7
plt.show(cross3.plot(kind='bar', title='Race by Workclass'))

In [ ]:
cross4 = pd.crosstab(adult_mod['race'], adult_mod['income'])
print cross4

plt.rcParams['figure.figsize'] = 10, 7
plt.show(cross4.plot(kind='bar', title='Income vs. Race'))

In [ ]:
cross5 = pd.crosstab(adult_mod['sex'], adult_mod['income'])
print cross5

plt.rcParams['figure.figsize'] = 10, 7
plt.show(cross5.plot(kind='bar', title='Gender vs. Income'))

#### It is clear that the private sector dominates in income with the most people over 50K. As far as race, we see a disparity in which the caucasian population trends higher. The male population also tends to have higer income overall, but a higher proportion of those below 50K as compared to females.

## B. 

### *Predictive Modeling and Model Evaluation:
Using either Pandas or Scikit-learn, create dummy variables for the categorical attributes. Then separate the target attribute ("income_>50K") from the attributes used for training. [Note: you need to drop "income_<=50K" which is also created as a dummy variable in earlier steps).

Use scikit-learn to build classifiers uisng Naive Bayes (Gaussian), decision tree (using "entropy" as selection criteria), and linear discriminant analysis (LDA). For each of these perform 10-fold cross-validation (using cross-validation module in scikit-learn) and report the overall average accuracy.

For the decision tree model (generated on the full training data), generate a visualization of tree and submit it as a separate file (png, jpg, or pdf) or embed it in the Jupyter Notebook.*

In [ ]:
adult_mod.describe(include='all')

In [ ]:
adultmod_sci = adult_mod
adultmod_sci.describe(include='all')

In [ ]:
adultmod_target = adultmod_sci.income
adultmod_target.head(10)

In [ ]:
adultmod_sci_dum = pd.get_dummies(adultmod_sci[['age', 'workclass', 'education', 'marital-status', 'race', 'sex', 'hours-per-week']])
adultmod_sci_dum.head()

In [ ]:
adult_train, adult_test, adult_target_train, adult_target_test = train_test_split(adultmod_sci_dum, adultmod_target, test_size = 0.2, random_state=33)

print adult_test.shape
adult_test.head()

In [ ]:
adultclf = tree.DecisionTreeClassifier(criterion='entropy', min_samples_split=3)
adultclf = adultclf.fit(adult_train, adult_target_train)

In [ ]:
adultpreds_test = adultclf.predict(adult_test)
print adultpreds_test

In [ ]:
print adultclf.score(adult_train, adult_target_train)

In [ ]:
print adultclf.score(adult_test, adult_target_test)

In [ ]:
ad_bayes = naive_bayes.GaussianNB()
ad_bayes = ad_bayes.fit(adult_train, adult_target_train)
ad_preds_test = ad_bayes.predict(adult_test)
print ad_preds_test

In [ ]:
print ad_bayes.score(adult_train, adult_target_train)

In [ ]:
print ad_bayes.score(adult_test, adult_target_test)

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
ad_lin = LinearDiscriminantAnalysis()
ad_lin = ad_lin.fit(adult_train, adult_target_train)
ad_lin_pred = ad_lin.predict(adult_test)
print ad_lin_pred

In [ ]:
print ad_lin.score(adult_test, adult_target_test)

In [ ]:
from sklearn import cross_validation

In [ ]:
cross = cross_validation.cross_val_score(adultclf, adultmod_sci_dum, adultmod_target, cv=10)

In [ ]:
print("Overall Accuracy: %0.2f (+/- %0.2f)" % (cross.mean(), cross.std()*2))

In [ ]:
cross_bayes = cross_validation.cross_val_score(ad_bayes, adultmod_sci_dum, adultmod_target, cv=10)

In [ ]:
print("Overall Accuracy: %0.2f (+/- %0.2f)" % (cross_bayes.mean(), cross_bayes.std()*2))

In [ ]:
cross_lda = cross_validation.cross_val_score(ad_lin, adultmod_sci_dum, adultmod_target, cv=10)

In [ ]:
print("Overall Accuracy: %0.2f (+/- %0.2f)" % (cross_lda.mean(), cross_bayes.std()*2))